# Generated by Django 4.2.7 on 2023-11-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_website', '0002_alter_project_youtube_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
