# Generated by Django 4.2.7 on 2023-11-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_website', '0003_alter_project_youtube_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
