# Generated by Django 4.2.7 on 2023-11-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_website', '0004_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
